### ISSUE TITLE
Start with the product selection

### ISSUE THREAD

**Issue by dgdavid** [yast/d-installer#200]
As proposed by @joseivanlopez in the context of https://github.com/yast/d-installer/pull/192, D-installer could start with a screen for selecting the product. It does not break the main idea of [starting with the summary](https://github.com/yast/yast-installation/issues/903), but just adds a preliminary step that could help to avoid an extra (and undesired) _probing_.

I like the idea, which we can materialize with a screen using  [`Cards`](https://www.patternfly.org/v4/components/card) or [`Tiles`](https://www.patternfly.org/v4/components/tile) rendering the product name, its description and even its logo. Something like the screenshot below, but improved.

<p align="center">
<img src="https://user-images.githubusercontent.com/1691872/174033384-20bb3427-62e6-44e4-adf4-67f664209e40.png" />
</p>

However, this challenge us to start thinking on a better navigation between screens.

## Tasks

- [X] Introduce react-router to have proper navigation.
- [x] Do not read the repositories until the installation starts (no need, by now, to fetch information from there).
- [x] If only one product is available, select such a product (by now, apply the same config to all services). If there are multiple products, do not make any proposal until one is selected.
- [X] Display a product selection screen when no product is selected (multiple products are available).
- [x] Reload the configuration when the user selects a different product (each service should listen for that signal).
